### ISSUE TITLE
A little bit more flexibility on urls for handle-function...

### ISSUE THREAD

**Issue by openWebX** [jacwright/RestServer#83]
In my case i just added the RestServer to a selfwritten API which already does rewrites and routing based on urls... 

Therefor i just needed to be able to use the handle-Method with a given url (not the REQUEST_URI)... 

i did it that way:
```
public function handle($path = null) {
        if (!$path) {
            $this->url = $this->getPath();
        } else {
            $this->url = $path;
        }
```

That way i can do my own routing and authorization and pass the rest of the url directly to the RestServer...

Perhaps somebody may need that also...

**Comment by tyzoid** [comment]
RestServer is designed to be a standalone library, not integrated with another. It looks like you are making this more as an informational post, but this will not be implemented without a significant refactor to reduce the ugliness factor of such a modification.

**Comment by openWebX** [comment]
Didn't realize that being a "standalone library" should make it impossible to be flexible to external vars for example... but ok, ack...

**Comment by tyzoid** [comment]
It doesn't necessarily mean that it's impossible. This library was not designed in a way that was easily modularizable. Basically, it was designed with the assumption that it handles routing, calling, loading, and processing. Implementing a bypass for any of these is certainly possible, but in order to properly accommodate this usage type, it would be better to properly modularize each of these components - something which would require more significant effort than a simple bypass.

Additionally, the way that the issue report was written looked more to me like an informational post than a feature request - if I've misinterpreted this, please feel free to clarify and reopen.

Hopefully that makes more sense.
